apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: movies-frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: movies-frontend
    spec:
      containers:
      - image: okteto/example-react
        name: movies-frontend