apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: payroll
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: payroll
    spec:
      containers:
      - image: okteto/payroll:0.1
        name: payroll